[build]
builder = "dockerfile"

[[services]]
name = "backend"
dockerfilePath = "backend/Dockerfile"
dockerContextPath = "backend"

[services.deploy]
healthcheckPath = "/health"
restartPolicyType = "on_failure"

[[services]]
name = "web"
dockerfilePath = "web/Dockerfile"
dockerContextPath = "web"

[services.deploy]
restartPolicyType = "on_failure"
